### ISSUE TITLE
migration command failure with something about $PGCLUSTER

### ISSUE THREAD

**Issue by pumazi** [Connexions/cnx-deploy#8]
## Summary

```
TASK [migrate database] ********************************************************
fatal: [cte-cnx-dev.cnx.org]: FAILED! => {"changed": true, "cmd": ["/var/cnx/venvs/publishing/bin/dbmigrator", "--config", "/etc/cnx/publishing/app.ini", "--context", "cnx-archive", "--context", "cnx-publishing", "migrate"], "delta": "0:00:00.372661", "end": "2016-02-13 13:39:26.529256", "failed": true, "rc": 1, "start": "2016-02-13 13:39:26.156595", "stderr": "Error: Invalid version specified with $PGCLUSTER\nTraceback (most recent call last):\n  File \"/var/cnx/venvs/publishing/bin/dbmigrator\", line 9, in <module>\n    load_entry_point('db-migrator==0.1.0', 'console_scripts', 'dbmigrator')()\n  File \"/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/dbmigrator/cli.py\", line 88, in main\n    return args['cmmd'](**args)\n  File \"/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/dbmigrator/utils.py\", line 81, in wrapper\n    return func(cursor, *args, **kwargs)\n  File \"/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/dbmigrator/commands/migrate.py\", line 30, in cli_command\n    migration)\n  File \"/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/dbmigrator/utils.py\", line 138, in compare_schema\n    ['pg_dump', '-s', db_connection_string]).decode('utf-8')\n  File \"/usr/lib/python2.7/subprocess.py\", line 573, in check_output\n    raise CalledProcessError(retcode, cmd, output=output)\nsubprocess.CalledProcessError: Command '['pg_dump', '-s', 'dbname=cnxarchive user=cnxarchive password=cnxarchive host=localhost port=5432']' returned non-zero exit status 1", "stdout": "", "stdout_lines": [], "warnings": []}
```

```pytb
Error: Invalid version specified with $PGCLUSTER
Traceback (most recent call last):
  File "/var/cnx/venvs/publishing/bin/dbmigrator", line 9, in <module>
    load_entry_point('db-migrator==0.1.0', 'console_scripts', 'dbmigrator')()
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/dbmigrator/cli.py", line 88, in main
    return args['cmmd'](**args)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/dbmigrator/utils.py", line 81, in wrapper
    return func(cursor, *args, **kwargs)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/dbmigrator/commands/migrate.py", line 30, in cli_command
    migration)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/dbmigrator/utils.py", line 138, in compare_schema
    ['pg_dump', '-s', db_connection_string]).decode('utf-8')
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['pg_dump', '-s', 'dbname=cnxarchive user=cnxarchive password=cnxarchive host=localhost port=5432']' returned non-zero exit status 1
```

## Environment

cte-dev

**Comment by pumazi** [comment]
This runs locally for both @karenc and myself. Maybe it's the VM?

**Comment by reedstrm** [comment]
Hard to debug without the environment, to see what $PGCLUSTER is set to. That's usually something like '9.4/main' to indicate the version and DB to operate on. Seems to be pointing at a version or db that doesn't exist.  Can I get reproducibility steps?

**Comment by pumazi** [comment]
Reproduce via `ansible-playbook -i environments/cte-dev/inventory main.yml --ask-become-pass`

**Comment by pumazi** [comment]
Or, if you'd rather just run the command: `/var/cnx/venvs/publishing/bin/dbmigrator --config /etc/cnx/publishing/app.ini --context cnx-archive --context cnx-publishing migrate`

**Comment by reedstrm** [comment]
raise Exception('db-connection-string missing')
Exception: db-connection-string missing

**Comment by pumazi** [comment]
Aha, looks like that's a different issue. The permissions on the config file are specific to my user. I'll fix that and ping you again when it's in.

**Comment by karenc** [comment]
Did you guys figure out what the issue is?

**Comment by pumazi** [comment]
I fixed the permissions issue. You should be able to try again.

**Comment by karenc** [comment]
```
/var/cnx/venvs/publishing/bin/dbmigrator --config /etc/cnx/publishing/app.ini --context cnx-archive --context cnx-publishing migrate
```

is working for me on cte dev.

**Comment by pumazi** [comment]
Ok, @karenc and I tried migrate and rollback. We can't get this issue to pop up again. I'm going to say it's resolved.

**Comment by pumazi** [comment]
Running into this again... We need to find out what is causing this. I seem to be running into it ever other time I run the deployment.

**Comment by pumazi** [comment]
My fault! :stuck_out_tongue_closed_eyes: I had `PGCLUSTER=9.3/main` in my `~/.bashrc` file. Problem solved.
